# Machine Learning Assignment No.3
## _To build a neural network-based classifier that can determine whether a bank customer will leave the bank or not in the next 6 months._
                                                                                       Author: Akib Faras
                                                                                       BE Computer Engineering

### _Importing Essential Libraries._

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

## 1 - Data Preprocessing

In [28]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## 2 - Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## 3 - Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5949 - accuracy: 0.7161
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4904 - accuracy: 0.7986
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4517 - accuracy: 0.8049
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4326 - accuracy: 0.8133
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4195 - accuracy: 0.8216
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4041 - accuracy: 0.8278
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3850 - accuracy: 0.8349
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3688 - accuracy: 0.8454
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3587 - accuracy: 0.8511
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3528 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8635
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3329 - accuracy: 0.8644
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8641
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3329 - accuracy: 0.8641
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8645
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8634
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8639
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8634
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8637
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 

## 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Using our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, the customer will leave the bank?

In [22]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 125ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

### Predicting the Test set results

In [23]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1523   72]
 [ 195  210]]


0.8665